### ISSUE TITLE
apiKey authentication: apiKey is not being passed in header

### ISSUE THREAD

**Issue by kumarz** [korser1/Swagger-Net.Examples#1]
I am using swagger-Net v 8.3.1.101 for .net 4.6.2 

I enabled api key authentication but the apiKey is not being passed in the header.
Code like below,

```
                        c.ApiKey("apiKey")
                            .Description("API Key Authentication")
                            .Name("apiKey")
                            .In("header");

                        c.EnableApiKeySupport("apiKey", "header");
```

**Comment by korser1** [comment]
This package is about examples for swagger, not for swagger itself.
You can see information about ApiKey here - https://github.com/korser1/Swagger-Net.Examples/blob/f3819b6831b93aed7c92bbd9de287f2a30e3414b/WebApi/SwaggerConfig.cs
